### ISSUE TITLE
BUG : problem when adding a new node

### ISSUE THREAD

**Issue by krisken** [wind-project/wind#69]
Hello,

I've just installed Wind v1.1-0-a1 on my website, and I get an error when adding a new node (first node) directly after the install : 

Parse error: syntax error, unexpected T_CONSTANT_ENCAPSED_STRING in /home/u0025/domains/wirelesswetteren.be/public_html/nodedb/wind/includes/pages/node_editor/node_editor.php on line 65 

Could you please let me know when this is fixed?  Thanks a lot!

**Comment by cirrusj** [comment]
Thanks for the bug report. There was a small problem with the quotes in line 65.

**Comment by krisken** [comment]
Hi Cirrusj,

Thank you for your very fast respons!
Could you please let me know how i can update Wind?  I'm not that familiar with Github/Git/...
I'm using Centos 6.6.

Best regards,
Kris

**Comment by cirrusj** [comment]
Did you do the initial installation by cloning the git repository or did you download the ZIP file?

**Comment by krisken** [comment]
Hello Cirrusj,

I did it by cloning the git repository : git clone https://github.com/wind-project/wind.git

Kris

**Comment by cirrusj** [comment]
Just getting into the wind directory and running `git pull` should work.
