### ISSUE TITLE
typo in nodes_plot.php

### ISSUE THREAD

**Issue by FezzFest** [wind-project/wind#72]
There is a missing `}` in includes/pages/nodes/nodes_plot.php. This causes PHP to throw a parsing error: `PHP Parse error:  syntax error, unexpected '?>', expecting function (T_FUNCTION) in /var/www/wind/includes/pages/nodes/nodes_plot.php on line 65, referer: http://10.94.176.70/index.php/nodes?node=3`.

**Comment by spinza** [comment]
Where is the typo?  I can't find it.  Looking to fix it as I get the same error.

**Comment by jammin84** [comment]
I would say an additional  }  on line 55 would resolve the issue.

The admins of this page dont seem to update things too often, so you may just need to code it in yourselves.

**Comment by spinza** [comment]
Thanks @jammin84 submitted a pull request to fix this.  I can't believe I was looking in the wrong file all the time.
