### ISSUE TITLE
Cannot register new user

### ISSUE THREAD

**Issue by nothingface0** [wind-project/wind#80]
The AWMN register page seems to be broken, making it impossible to create a new user.

**Comment by jammin84** [comment]
@nothingface0 can you please provide further information to what the AWMN register page is?

A link or screenshot as to what is "broken" helps a lot.

I'm otherwise not aware of any issues with the new user registration system within WiND.

**Comment by jammin84** [comment]
@nothingface0 perhaps take a look at the forked project https://github.com/southern-wind/wind

**Comment by jbonicioli** [comment]
The AWMN link is to the portal of the Athens Wireless Metropolitan Network. You do not need to register to that to use wind. I am not even sure why is that there. If that is what it is.
@jammin84 have you forked a latest code or have you forked something back in 2015 as you describe in you README? There are numerous improvements since then and it would be nice to see you work on the latest code.

**Comment by nothingface0** [comment]
Hey guys, sorry, [here ](http://awmn.net/register.php)is the page and [here ](http://i.imgur.com/okii4qN.png)is what it looks like. 

At the forums I read that the first thing to do is register, so I guessed it would be important?

**Comment by spinza** [comment]
That's not wind.

**Comment by nothingface0** [comment]
@spinza So is this project completely unrelated? Should I delete this issue?

**Comment by nothingface0** [comment]
Ok, now I understand. I confused what is what, haha. Sorry for this! And thanks for the answers.

**Comment by spinza** [comment]
Yep,  that page is not part of WiND.

On Mon, 04 Jul 2016, 08:59 nothingface0 <notifications@github.com> wrote:

> Ok, now I understand. I confused what is what, haha. Sorry for this! And
> thanks for the answers.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/wind-project/wind/issues/80#issuecomment-230218943>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADVuHoniq5XuW_zAWkYLNnfztAqN6rAwks5qSK8-gaJpZM4JDnuv>
> .
>
-- 
__
Louis Rossouw
+27 82 498 7214
