### ISSUE TITLE
tools/update.php error

### ISSUE THREAD

**Issue by senortiago** [wind-project/wind#81]
I used the update script through cli as suggested and..

Schema is currently at v1.0 version
Upgrading DB Schema to v1.1...

`ALTER TABLE 'links' CHANGE COLUMN 'status' 'enum('active','inactive','pending')' Array  Error                                 executing SQL query: You have an error in your SQL syntax; check the manual that corresponds                                 to your MySQL server version for the right syntax to use near 'Array' at line 1`

**Comment by jammin84** [comment]
@senortiago this issue is resolved in the forked Southern-Wind - https://github.com/southern-wind/wind

**Comment by senortiago** [comment]
@jammin84 thanks
